#!/bin/sh

startdir=`pwd`

if [ ! -d "src/common/bower_components" ]; then
    cd src/common
    bower install
    mv src/common/bower_components ./
    rm -rf src
else
    echo "src/common/bower_components already exists.  skipping..."
fi

cd $startdir

if [ ! -d "src/app/bower_components" ]; then
    cd src/app
    bower install
    mv src/common/bower_components ./
    rm -rf src
else
    echo "src/app/bower_components already exists. skipping..."
fi
